### ISSUE TITLE
Where can I find the Data and The Labels

### ISSUE THREAD

**Issue by akshaylamba** [LilyHu/image_segmentation_chromosomes#1]
Hi 

Where can I find the Data and The Labels for review purpose..it will help me better in understanding the code...

**Comment by LilyHu** [comment]
The data and labels can be found on: http://ai-on.org/projects/visual-segmentation-of-chromosomal-preparations.html under the Dataset heading. The direct link is https://www.kaggle.com/jeanpat/overlapping-chromosomes/downloads/overlapping-chromosomes.zip
