### ISSUE TITLE
The prediction output

### ISSUE THREAD

**Issue by khaopod** [LilyHu/image_segmentation_chromosomes#3]
Hi,
I've already trained the model and also trying it out but I am confuse about the prediction output. can you explain the output?.

**Comment by LilyHu** [comment]
The prediction output has the same width and height as the input image so that each pixel in the input image has a corresponding prediction in the output. The output has depth 4 for the 4 possible classes: no chromosome, 1st chromosome, 2nd chromosome, both chromosomes.
