### ISSUE TITLE
thoughts on an arbitrary number of classes?

### ISSUE THREAD

**Issue by bw4sz** [LilyHu/image_segmentation_chromosomes#4]
Hi Lily,

Thanks for making this source available. I'm working on a similar keras project in classifying trees from airborne images. Each image has many overlapping tree crowns, and I have ground truth layers that are fed into a Unet. I'm wondering if you've given any thought or have suggestions about what would happen if you had an unknown number of chromosomes. In all your pictures you have label 1,2,3. Have you ever seen a similar example of semantic segmentation + clustering to decide object boundaries? All thoughts welcome.

**Comment by LilyHu** [comment]
Hi,

A simple idea to start is to increase the number of classes to take into account the max number of trees or max number of overlapping trees.
