### ISSUE TITLE
Where is the chromosome data set come from?

### ISSUE THREAD

**Issue by ShaoCorn** [LilyHu/image_segmentation_chromosomes#6]
Excuse me, I am a student of Southern University of Science and Technology(SUSTech). I am interested in your chromosome research there and would like to repeat it by myself. But I can not find where is the chromosome data set, could you share the data with me?

**Comment by LilyHu** [comment]
The data is available on the link here:
https://ai-on.org/2016/10/01/visual-segmentation-of-chromosomal-preparations/

**Comment by ShaoCorn** [comment]
Thank you!☺

**Comment by ShaoCorn** [comment]
Em...It is the first time that I use the .h5 file and I had tried many ways to extract the data/images. However I can't find a way to do that. Could you tell me how to process the .h5 file? Thank you!
